name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i

      - run: npm run build

        env:
          CI: false

      - run: pm2 delete jobby_client

      - run: pm2 start npm --name "jobby_client" -- run serve --spa

      - run: |
          pm2 start jobby_client
          pm2 save
          pm2 resurrect
          sudo service nginx restart
